[general]
live_config_reload = true
import = ["bindings.toml" ]

[env]
TERM = "xterm-256color"

[window]
decorations = "full"
dynamic_padding = true
opacity = 1.0
startup_mode = "Windowed"

[window.padding]
x = 5
y = 5

[window.dimensions]
columns = 120
lines = 40

[scrolling]
history = 600
multiplier = 3

[font]
size = 10

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font Mono"

[font.offset]
x = 0
y = 0

[colors]
draw_bold_text_with_bright_colors = false 

[bell]
animation = "EaseOutExpo"
color = "#ffffff"
duration = 0

[selection]
save_to_clipboard = false
semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[cursor]
style = "Beam"
unfocused_hollow = true

[terminal.shell]
args = ["-l"]
program = "/bin/zsh"

[mouse]
hide_when_typing = true

[debug]
renderer = "None" # "glsl3" | "gles2" | "gles2pure" | "None" 
